# Generated by Django 5.1.5 on 2025-02-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_tel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
