# Generated by Django 5.1.5 on 2025-02-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
