# Generated by Django 5.1.5 on 2025-01-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bigMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ("icon_img", models.ImageField(max_length=600, upload_to='icon/')),
                ('img', models.ImageField(max_length=600, upload_to='bigmenu/')),
            ],
        ),
        migrations.CreateModel(
            name='smallMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(max_length=600, upload_to='smallmenu/')),
                ('bigmenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.bigmenu')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(max_length=600, upload_to='product/')),
                ('smallmenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.smallmenu')),
            ],
        ),
    ]
