# Generated by Django 5.1.5 on 2025-01-17 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(max_length=600, upload_to='aksiya/')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('stoldagi_orindiq_soni', models.IntegerField()),
                ('is_aviable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='smallmenu',
            new_name='smallMenu',
        ),
        migrations.RenameField(
            model_name='smallmenu',
            old_name='bigmenu',
            new_name='bigMenu',
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(max_length=600, upload_to='newfoods/')),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('is_new', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('smallMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.smallmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurma_sanasi', models.DateTimeField()),
                ('maxsus_sorovlar', models.TextField(blank=True, max_length=1000, null=True)),
                ('mehmonlar_soni', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(
                    choices=[('kutish', 'Kutish'), ('tolandi', "To'landi"), ('tolanmagan', "To'lanmagan")],
                    default="To'lanmagan", max_length=100)),
                ('customer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tables')),
            ],
        ),
    ]
