# Generated by Django 5.1.5 on 2025-01-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigmenu',
            name='icon_url',
        ),
    ]
