# Generated by Django 5.1.5 on 2025-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_bigmenu_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='old_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
