# Generated by Django 5.1.5 on 2025-02-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_newproduct_old_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aksiya',
        ),
        migrations.RemoveField(
            model_name='smallmenu',
            name='bigMenu',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='smallMenu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
        migrations.RemoveField(
            model_name='product',
            name='smallMenu',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='bigMenu',
        ),
        migrations.DeleteModel(
            name='NewProduct',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='smallMenu',
        ),
    ]
