# Generated by Django 5.1.5 on 2025-02-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0009_delete_aksiya_remove_smallmenu_bigmenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(max_length=600, upload_to='aksiya/')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BigMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon_img', models.ImageField(max_length=600, upload_to='icon/')),
                ('img', models.ImageField(max_length=600, upload_to='bigmenu/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(max_length=600, upload_to='Slider/')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('stoldagi_orindiq_soni', models.IntegerField()),
                ('is_aviable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmallMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(max_length=600, upload_to='smallmenu/')),
                ('bigMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.bigmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(max_length=600, upload_to='product/')),
                ('smallMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.smallmenu')),
            ],
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(max_length=600, upload_to='newfoods/')),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('sale', models.BooleanField(default=False)),
                ('smallMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.smallmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('fmiliasi', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('buyurma_sanasi', models.DateTimeField()),
                ('mehmonlar_soni', models.PositiveIntegerField()),
                ('maxsus_sorovlar', models.TextField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.tables')),
            ],
        ),
    ]
