# Generated by Django 5.1.5 on 2025-02-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mehmonlar_soni',
        ),
        migrations.AddField(
            model_name='order',
            name='kim_bn',
            field=models.CharField(choices=[("do'stim bilan", "Do'sti bilan"), ('sevgan qizim(Yigitim) bilan', 'Sevgan Qizim(Yigitim) bilan'), ('qarindoshlarim bilan', 'Qarindoshlarim bilan'), ("faqat o'zim", "Faqat o'zim")], default="o'zim"),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.IntegerField(),
        ),
    ]
